import * as dotenv from "dotenv";
dotenv.config();
import { getDb } from "../server/db";
import { events } from "../drizzle/schema";

console.log("시드가 연결하는 DB:", process.env.DATABASE_URL);

const db = await getDb();


const eventsData = [
  {
    id: 30008,
    name: "2026 메이커앤하비 페스티벌",
    description: "제주에서 열리는 대규모 서브컬처 축제로, 2차 창작 굿즈 전시 및 판매, 코스프레 경연 대회, 메이커 창작품 전시/체험 등 다양한 프로그램으로 구성됩니다.",
    eventDate: "2026-06-06T10:30:00.000Z",
    eventEndDate: "2026-06-07T00:00:00.000Z",
    location: "제주 사라봉 다목적체육관",
    region: "제주",
    ticketOpenDate: "2026-05-01T00:00:00.000Z",
    ticketLink: null,
    mapLink: "https://litt.ly/makernhobby",
    allowsCosplay: "yes",
  },
  {
    id: 90001,
    name: "COSFE T21 2026",
    description: "서울 문화비축기지에서 열리는 코스프레 페스티벌. 코스프레 대회(총 상금 1,600만 원), 공연, 포토타임, 퍼레이드 등 다양한 프로그램이 진행됩니다.",
    eventDate: "2026-07-11T00:00:00.000Z",
    eventEndDate: "2026-07-12T00:00:00.000Z",
    location: "서울 마포구 문화비축기지",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: "https://tickets.interpark.com/contents/notice/detail/13836",
    mapLink: null,
    allowsCosplay: "yes",
  },
  {
    id: 1,
    name: "코믹월드 SUMMER 2026",
    description: "대한민국 대표 동인 행사 코믹월드! 아마추어 만화가들이 직접 창작한 만화창작품을 전시 및 판매하는 이벤트입니다.",
    eventDate: "2026-07-18T11:00:00.000Z",
    eventEndDate: "2026-07-19T00:00:00.000Z",
    location: "일산 킨텍스 제1전시장",
    region: "일산",
    ticketOpenDate: "2026-06-01T00:00:00.000Z",
    ticketLink: "https://comicw.net/shop/item.php?it_id=1775781342",
    mapLink: "https://comicw.net/e/334/8",
    allowsCosplay: "yes",
  },
  {
    id: 60002,
    name: "제34회 디.페스타",
    description: "서울에서 개최되는 동인지 판매 행사입니다. 다양한 창작자들의 동인지와 굿즈를 만나볼 수 있습니다.",
    eventDate: "2026-07-25T11:00:00.000Z",
    eventEndDate: null,
    location: "서울 코엑스",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://dongne.co/events/df260702",
    allowsCosplay: "no",
  },
  {
    id: 60001,
    name: "스카이코드 페스티벌 32회",
    description: "광주 지역에서 개최되는 동인 행사로, 코스프레 무대전과 전국덕후노래자랑이 진행됩니다.",
    eventDate: "2026-07-26T11:00:00.000Z",
    eventEndDate: null,
    location: "광주디자인진흥원 이벤트홀 2층 전시장 및 야외 일대",
    region: "광주",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://x.com/SKYCHORD_160111/status/2052347940396847544",
    allowsCosplay: "yes",
  },
  {
    id: 60003,
    name: "일러스타 페스 12",
    description: "2026년 8월 부산 벡스코에서 개최되는 종합 서브컬처 이벤트입니다.",
    eventDate: "2026-08-01T11:00:00.000Z",
    eventEndDate: null,
    location: "부산 벡스코",
    region: "부산",
    ticketOpenDate: null,
    ticketLink: "https://illustar.net",
    mapLink: "https://illustar.net/event-info/introduction",
    allowsCosplay: "yes",
  },
  {
    id: 60004,
    name: "코믹월드 335 일산",
    description: "일산 킨텍스에서 개최되는 코믹월드 행사입니다.",
    eventDate: "2026-08-15T11:00:00.000Z",
    eventEndDate: "2026-08-16T00:00:00.000Z",
    location: "일산 킨텍스 제1전시장",
    region: "일산",
    ticketOpenDate: null,
    ticketLink: "https://comicw.net/shop/item.php?it_id=1775781350",
    mapLink: "https://comicw.net/e/335/8",
    allowsCosplay: "yes",
  },
  {
    id: 60005,
    name: "스카이코드 페스티벌 2026 가을",
    description: "스카이코드 주최 동인행사/촬영회/라이브 공연 페스티벌.",
    eventDate: "2026-09-06T11:00:00.000Z",
    eventEndDate: null,
    location: "광주디자인진흥원",
    region: "광주",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://x.com/SKYCHORD_160111",
    allowsCosplay: "yes",
  },
  {
    id: 60007,
    name: "JUC 페스티벌 2026",
    description: "광주에서 개최되는 종합 서브컬처 페스티벌입니다.",
    eventDate: "2026-09-10T11:00:00.000Z",
    eventEndDate: null,
    location: "광주 김대중컨벤션센터",
    region: "광주",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: null,
    allowsCosplay: "yes",
  },
  {
    id: 60006,
    name: "코믹월드 336 일산",
    description: "일산 킨텍스에서 개최되는 코믹월드 행사입니다.",
    eventDate: "2026-09-12T11:00:00.000Z",
    eventEndDate: "2026-09-13T00:00:00.000Z",
    location: "일산 킨텍스 제1전시장",
    region: "일산",
    ticketOpenDate: null,
    ticketLink: "https://comicw.net/shop/item.php?it_id=1775781353",
    mapLink: "https://comicw.net/e/336/8",
    allowsCosplay: "yes",
  },
  {
    id: 60008,
    name: "코믹월드 337 울산",
    description: "울산전시컨벤션센터에서 개최되는 코믹월드 행사입니다.",
    eventDate: "2026-10-03T11:00:00.000Z",
    eventEndDate: "2026-10-04T00:00:00.000Z",
    location: "울산전시컨벤션센터",
    region: "울산",
    ticketOpenDate: null,
    ticketLink: "https://comicw.net",
    mapLink: "https://comicw.net",
    allowsCosplay: "yes",
  },
  {
    id: 60009,
    name: "제35회 디.페스타",
    description: "서울에서 개최되는 동인지 판매 행사입니다.",
    eventDate: "2026-10-03T11:00:00.000Z",
    eventEndDate: null,
    location: "서울 코엑스",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://dongne.co/events/df2610",
    allowsCosplay: "no",
  },
  {
    id: 60010,
    name: "코미버스 2026 가을",
    description: "서울에서 개최되는 동인 창작 배포전입니다.",
    eventDate: "2026-10-24T11:00:00.000Z",
    eventEndDate: null,
    location: "서울 코엑스",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://www.instagram.com/p/DY5wzLLk__F/",
    allowsCosplay: "no",
  },
  {
    id: 60011,
    name: "Anime X Game Festival 2026",
    description: "일산 킨텍스에서 개최되는 애니메이션·게임 종합 페스티벌입니다.",
    eventDate: "2026-12-04T11:00:00.000Z",
    eventEndDate: null,
    location: "일산 킨텍스",
    region: "일산",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: null,
    allowsCosplay: "limited",
  },
  {
    id: 60012,
    name: "2026 서울팝콘 (Seoul POPCON)",
    description: "코엑스에서 열리는 종합 팝컬처 컨벤션. 게임콘, 코믹콘, 라이브콘으로 구성되며 만화·웹툰·애니·캐릭터·코스플레이 등을 즐길 수 있습니다.",
    eventDate: "2026-08-14T10:00:00.000Z",
    eventEndDate: "2026-08-16T00:00:00.000Z",
    location: "서울 코엑스(COEX)",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://seoulpopcon.org/seoulpopcon",
    allowsCosplay: "yes",
  },
  {
    id: 60013,
    name: "제29회 부천국제만화축제 (BICOF)",
    description: "부천 한국만화박물관 일원에서 열리는 국제 만화 축제. 부천만화대상 수상작 전시, 창작음악제와 함께 경기국제코스프레페스티벌이 동시 개최됩니다.",
    eventDate: "2026-09-18T10:00:00.000Z",
    eventEndDate: "2026-09-20T00:00:00.000Z",
    location: "부천 한국만화박물관 일원",
    region: "부천",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://www.bicof.com/content/69.do",
    allowsCosplay: "yes",
  },
  {
    id: 60014,
    name: "제91회 코스앤코믹 페스티벌 (코코페)",
    description: "서울랜드에서 열리는 코스프레 중심의 동인 페스티벌. 코스프레 무대와 포토타임 등 다양한 프로그램이 진행됩니다.",
    eventDate: "2026-06-27T11:00:00.000Z",
    eventEndDate: "2026-06-28T00:00:00.000Z",
    location: "경기 과천 서울랜드",
    region: "경기",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://x.com/cos_comic",
    allowsCosplay: "yes",
  },
  {
    id: 60015,
    name: "제11회 대운동회 (동네 스포츠 온리전)",
    description: "동인 네트워크 '동네'가 주최하는 스포츠 장르 통합 온리전입니다.",
    eventDate: "2026-07-26T11:00:00.000Z",
    eventEndDate: null,
    location: "양재 aT센터",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://dongne.co/events/sports11",
    allowsCosplay: "no",
  },
  {
    id: 60016,
    name: "제9회 쩜오 어워드 (동네 실사매체 통합 온리전)",
    description: "동인 네트워크 '동네'가 주최하는 실사 매체 통합 온리전입니다.",
    eventDate: "2026-10-04T11:00:00.000Z",
    eventEndDate: null,
    location: "서울 SETEC",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://dongne.co/events/25d09",
    allowsCosplay: "no",
  },
  {
    id: 60017,
    name: "스크롤의 바다 3화 (동네 웹툰 원작 온리전)",
    description: "동인 네트워크 '동네'가 주최하는 웹툰 원작 작품 온리전입니다.",
    eventDate: "2026-10-04T11:00:00.000Z",
    eventEndDate: null,
    location: "서울 SETEC",
    region: "서울",
    ticketOpenDate: null,
    ticketLink: null,
    mapLink: "https://dongne.co/events/wt03",
    allowsCosplay: "no",
  },
];

async function main() {
  await db.delete(events);
  console.log("행사 데이터 입력 시작...");
  
  for (const event of eventsData) {
    // DB 스키마(schema.ts)에 존재하는 컬럼만 골라서 안전하게 매핑합니다.
    // 스키마에 없는 eventEndDate는 DB에 전달되지 않도록 아예 제외했습니다.
    const formattedEvent = {
      id: event.id,
      name: event.name,
      description: event.description,
      eventDate: new Date(event.eventDate),
      location: event.location,
      region: event.region,
      
      // 티켓 예매 일정이 아직 없는 행사는 임시로 2027년 1월 1일 오전 0시를 넣습니다.
      ticketOpenDate: event.ticketOpenDate ? new Date(event.ticketOpenDate) : new Date("2027-01-01T00:00:00.000Z"),
      
      ticketLink: event.ticketLink,
      mapLink: event.mapLink,
      allowsCosplay: event.allowsCosplay as "yes" | "no" | "limited",
      
      // 스키마에서 필수(notNull)로 요구하는 생성자 ID를 임의로 추가합니다.
      createdBy: 1, 
    };

    // 예쁘게 포장된 데이터를 DB에 삽입합니다.
    await db.insert(events).values(formattedEvent);
  }

  console.log("완료! 총 " + eventsData.length + "개 행사 입력됨");
}

main().catch(console.error);
